on:
  push:
    
jobs:
  Validators:
    name: Validators
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Python3
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependecies
      run: |
        python -m pip install html5validator linkchecker
        python setup.py sdist --manifest-only
        python setup.py build
        sudo python setup.py install

    - name: html5validator
      run: |
        html5validator --root docs/

    - name: linkchecker
      run: |
        linkchecker --check-extern docs/