name: Validation Tests

on:
  push:
    paths:
      - 'docs/**'
    
jobs:
  Validators:
    name: Validators
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Python3
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependecies
      run: |
        python3 -m venv env
        source env/bin/activate
        python -m pip install html5validator linkchecker

    - name: Validator Script
      run: |
        sudo chmod +x bin/validators.sh
        ./bin/validators.sh
